import * as React from 'react'
import { useActiveGame } from '../state/ActiveGameProvider'
import { cssVarStyle } from '../lib/theme'
import { Nav } from './Nav'

interface Props {
  children: React.ReactNode
  pageProps?: { pageContext?: { gameId?: string }; path?: string }
}

export function Layout({ children, pageProps }: Props): React.ReactElement {
  const { activeTheme, activeGameId, setActiveGame } = useActiveGame()

  // Pages generated by gatsby-node carry pageContext.gameId. Sync that into
  // the active-game state so a fresh page load (or refresh) sets the theme
  // correctly before any user interaction.
  React.useEffect(() => {
    const ctxGameId = pageProps?.pageContext?.gameId
    if (ctxGameId && ctxGameId !== activeGameId) {
      setActiveGame(ctxGameId)
    }
  }, [pageProps?.pageContext?.gameId, activeGameId, setActiveGame])

  return (
    <div className="tcgdb-app" style={cssVarStyle(activeTheme)}>
      <Nav />
      <main className="tcgdb-main">{children}</main>
    </div>
  )
}
